let preguntas = [
  // --- HISTORIA Y ARGENTINA (20) ---
  { pregunta: "¿Cuál es la capital de Argentina?", opciones: ["Córdoba", "Rosario", "Buenos Aires", "Mendoza"], correcta: "Buenos Aires" },
  { pregunta: "¿Cuántas provincias tiene Argentina?", opciones: ["20", "22", "23", "25"], correcta: "23" },
  { pregunta: "¿Qué cordillera recorre Argentina de norte a sur?", opciones: ["Alpes", "Andes", "Pirineos", "Apeninos"], correcta: "Andes" },
  { pregunta: "¿Qué océano baña las costas argentinas?", opciones: ["Atlántico", "Pacífico", "Índico", "Ártico"], correcta: "Atlántico" },
  { pregunta: "¿Qué prócer argentino creó la bandera?", opciones: ["San Martín", "Belgrano", "Rivadavia", "Sarmiento"], correcta: "Belgrano" },
  { pregunta: "¿En qué año fue la Revolución de Mayo?", opciones: ["1810", "1816", "1820", "1830"], correcta: "1810" },
  { pregunta: "¿Qué país limita al oeste con Argentina?", opciones: ["Uruguay", "Chile", "Brasil", "Paraguay"], correcta: "Chile" },
  { pregunta: "¿Cuál es el río más largo de Argentina?", opciones: ["Río Paraná", "Río Uruguay", "Río de la Plata", "Río Colorado"], correcta: "Río Paraná" },
  { pregunta: "¿Qué animal es símbolo nacional de Argentina?", opciones: ["Cóndor", "Jaguar", "Caballo", "Hornero"], correcta: "Hornero" },
  { pregunta: "¿Qué deporte es el más popular en Argentina?", opciones: ["Tenis", "Fútbol", "Básquet", "Hockey"], correcta: "Fútbol" },
  { pregunta: "¿Qué provincia argentina es conocida por sus cataratas?", opciones: ["Misiones", "Salta", "Jujuy", "Corrientes"], correcta: "Misiones" },
  { pregunta: "¿Qué prócer cruzó los Andes?", opciones: ["Belgrano", "San Martín", "Sarmiento", "Rivadavia"], correcta: "San Martín" },
  { pregunta: "¿Cuándo se declaró la independencia argentina?", opciones: ["1810", "1816", "1824", "1850"], correcta: "1816" },
  { pregunta: "¿En qué ciudad se firmó la independencia argentina?", opciones: ["Buenos Aires", "Córdoba", "Tucumán", "Mendoza"], correcta: "Tucumán" },
  { pregunta: "¿Qué presidente impulsó la Ley 1420 de educación?", opciones: ["Roca", "Sarmiento", "Mitre", "Alvear"], correcta: "Roca" },
  { pregunta: "¿Qué batalla selló la independencia sudamericana?", opciones: ["Ayacucho", "Maipú", "Chacabuco", "Junín"], correcta: "Ayacucho" },
  { pregunta: "¿Qué mujer argentina fue primera dama y símbolo popular?", opciones: ["Evita Perón", "Cecilia Grierson", "Juana Azurduy", "Alicia Moreau"], correcta: "Evita Perón" },
  { pregunta: "¿Qué día se conmemora el Día de la Bandera?", opciones: ["20 de junio", "9 de julio", "25 de mayo", "17 de agosto"], correcta: "20 de junio" },
  { pregunta: "¿Quién fue el primer presidente de Argentina?", opciones: ["Rivadavia", "San Martín", "Sarmiento", "Mitre"], correcta: "Rivadavia" },
  { pregunta: "¿Qué guerra enfrentó a Argentina y el Reino Unido por las Malvinas?", opciones: ["Guerra del Chaco", "Guerra de las Malvinas", "Guerra del Pacífico", "Guerra Civil"], correcta: "Guerra de las Malvinas" },

  // --- CIENCIAS Y NATURALEZA (20) ---
  { pregunta: "¿Cuál es el planeta más cercano al Sol?", opciones: ["Venus", "Mercurio", "Marte", "Tierra"], correcta: "Mercurio" },
  { pregunta: "¿Qué gas respiramos los seres humanos?", opciones: ["Oxígeno", "Hidrógeno", "Nitrógeno", "Helio"], correcta: "Oxígeno" },
  { pregunta: "¿Qué animal es el más grande del planeta?", opciones: ["Elefante", "Ballena azul", "Tiburón blanco", "Orca"], correcta: "Ballena azul" },
  { pregunta: "¿Cuántos huesos tiene el cuerpo humano adulto?", opciones: ["200", "206", "210", "220"], correcta: "206" },
  { pregunta: "¿Qué órgano bombea la sangre?", opciones: ["Pulmón", "Hígado", "Corazón", "Riñón"], correcta: "Corazón" },
  { pregunta: "¿Qué planeta es conocido como el planeta rojo?", opciones: ["Júpiter", "Venus", "Marte", "Saturno"], correcta: "Marte" },
  { pregunta: "¿Qué parte de la planta realiza la fotosíntesis?", opciones: ["Raíz", "Tallo", "Hoja", "Flor"], correcta: "Hoja" },
  { pregunta: "¿Qué tipo de animal es el pingüino?", opciones: ["Mamífero", "Ave", "Reptil", "Anfibio"], correcta: "Ave" },
  { pregunta: "¿Qué gas exhalamos al respirar?", opciones: ["Nitrógeno", "Oxígeno", "Dióxido de carbono", "Hidrógeno"], correcta: "Dióxido de carbono" },
  { pregunta: "¿Qué órgano del cuerpo humano produce insulina?", opciones: ["Páncreas", "Hígado", "Riñón", "Pulmón"], correcta: "Páncreas" },
  { pregunta: "¿Cuál es el metal más liviano?", opciones: ["Hierro", "Cobre", "Litio", "Plomo"], correcta: "Litio" },
  { pregunta: "¿Qué inventó Alexander Graham Bell?", opciones: ["Radio", "Teléfono", "Televisión", "Bombilla"], correcta: "Teléfono" },
  { pregunta: "¿Qué instrumento mide la temperatura?", opciones: ["Barómetro", "Termómetro", "Anemómetro", "Altímetro"], correcta: "Termómetro" },
  { pregunta: "¿Qué planeta tiene anillos visibles?", opciones: ["Saturno", "Júpiter", "Urano", "Neptuno"], correcta: "Saturno" },
  { pregunta: "¿Qué fuerza nos mantiene en la Tierra?", opciones: ["Magnetismo", "Gravedad", "Presión", "Electricidad"], correcta: "Gravedad" },
  { pregunta: "¿Qué nombre recibe el satélite natural de la Tierra?", opciones: ["Luna", "Sol", "Venus", "Marte"], correcta: "Luna" },
  { pregunta: "¿Qué órgano del cuerpo humano filtra la sangre?", opciones: ["Riñón", "Pulmón", "Hígado", "Estómago"], correcta: "Riñón" },
  { pregunta: "¿Qué líquido circula por las venas?", opciones: ["Agua", "Sangre", "Plasma", "Oxígeno"], correcta: "Sangre" },
  { pregunta: "¿Qué animal pone huevos?", opciones: ["Gato", "Gallina", "Perro", "Vaca"], correcta: "Gallina" },
  { pregunta: "¿Qué planeta es el más grande del sistema solar?", opciones: ["Saturno", "Júpiter", "Urano", "Neptuno"], correcta: "Júpiter" },

  // --- CULTURA Y ARTE (20) ---
  { pregunta: "¿Quién pintó la Mona Lisa?", opciones: ["Picasso", "Da Vinci", "Van Gogh", "Rembrandt"], correcta: "Da Vinci" },
  { pregunta: "¿Qué idioma se habla en Brasil?", opciones: ["Español", "Portugués", "Inglés", "Francés"], correcta: "Portugués" },
  { pregunta: "¿Qué instrumento tiene teclas blancas y negras?", opciones: ["Guitarra", "Violín", "Piano", "Batería"], correcta: "Piano" },
  { pregunta: "¿Qué obra escribió William Shakespeare?", opciones: ["Don Quijote", "Hamlet", "La Odisea", "El Principito"], correcta: "Hamlet" },
  { pregunta: "¿Quién escribió 'El Martín Fierro'?", opciones: ["Sarmiento", "Echeverría", "José Hernández", "Borges"], correcta: "José Hernández" },
  { pregunta: "¿Qué autor escribió 'El Principito'?", opciones: ["Saint-Exupéry", "Andersen", "Carroll", "Verne"], correcta: "Saint-Exupéry" },
  { pregunta: "¿Cuál es el género musical típico del Río de la Plata?", opciones: ["Cumbia", "Tango", "Rock", "Folklore"], correcta: "Tango" },
  { pregunta: "¿Qué famoso pintor se cortó una oreja?", opciones: ["Picasso", "Van Gogh", "Monet", "Dalí"], correcta: "Van Gogh" },
  { pregunta: "¿Qué instrumento musical usa cuerdas y arco?", opciones: ["Violín", "Piano", "Trompeta", "Batería"], correcta: "Violín" },
  { pregunta: "¿Qué lengua se habla en la mayor parte de América del Sur?", opciones: ["Inglés", "Español", "Francés", "Portugués"], correcta: "Español" },
  { pregunta: "¿Qué poeta escribió 'Don Segundo Sombra'?", opciones: ["Lugones", "Güiraldes", "Borges", "Cortázar"], correcta: "Güiraldes" },
  { pregunta: "¿Qué artista argentino es conocido por 'Mafalda'?", opciones: ["Fontanarrosa", "Quino", "Caloi", "Sendra"], correcta: "Quino" },
  { pregunta: "¿Qué tipo de arte realiza un escultor?", opciones: ["Pintura", "Escultura", "Música", "Danza"], correcta: "Escultura" },
  { pregunta: "¿Qué color se obtiene mezclando azul y amarillo?", opciones: ["Verde", "Rojo", "Violeta", "Naranja"], correcta: "Verde" },
  { pregunta: "¿Qué país es famoso por el sushi?", opciones: ["China", "Japón", "Corea", "Tailandia"], correcta: "Japón" },
  { pregunta: "¿Qué instrumento musical usa percusión?", opciones: ["Batería", "Guitarra", "Violín", "Piano"], correcta: "Batería" },
  { pregunta: "¿Quién escribió 'Cien años de soledad'?", opciones: ["Borges", "Cortázar", "García Márquez", "Vargas Llosa"], correcta: "García Márquez" },
  { pregunta: "¿Qué país inventó el tango?", opciones: ["Uruguay", "Argentina", "Brasil", "Chile"], correcta: "Argentina" },
  { pregunta: "¿Qué día se celebra el Día del Maestro en Argentina?", opciones: ["11 de septiembre", "9 de julio", "25 de mayo", "20 de junio"], correcta: "11 de septiembre" },
  { pregunta: "¿Quién es el autor de 'Rayuela'?", opciones: ["Cortázar", "Borges", "Quiroga", "Sabato"], correcta: "Cortázar" },
  { pregunta: "¿Qué artista pintó 'La persistencia de la memoria'?", opciones: ["Dalí", "Picasso", "Van Gogh", "Monet"], correcta: "Dalí" },

  // --- GEOGRAFÍA MUNDIAL (10) ---
  { pregunta: "¿Cuál es la capital de Francia?", opciones: ["Roma", "Madrid", "París", "Londres"], correcta: "París" },
  { pregunta: "¿Cuál es la capital de Italia?", opciones: ["Roma", "Milán", "Venecia", "Nápoles"], correcta: "Roma" },
  { pregunta: "¿Cuál es la capital de España?", opciones: ["Barcelona", "Madrid", "Sevilla", "Bilbao"], correcta: "Madrid" },
  { pregunta: "¿Qué continente es el más grande?", opciones: ["América", "Asia", "Europa", "África"], correcta: "Asia" },
  { pregunta: "¿Cuál es el país más poblado del mundo?", opciones: ["China", "India", "EE.UU.", "Indonesia"], correcta: "China" },
  { pregunta: "¿En qué continente está Egipto?", opciones: ["Asia", "África", "Europa", "Oceanía"], correcta: "África" },
  { pregunta: "¿Qué país tiene forma de bota?", opciones: ["España", "Italia", "Grecia", "Francia"], correcta: "Italia" },
  { pregunta: "¿Cuál es el río más largo del mundo?", opciones: ["Nilo", "Amazonas", "Misisipi", "Yangtsé"], correcta: "Amazonas" },
  { pregunta: "¿Cuál es el desierto más grande del mundo?", opciones: ["Kalahari", "Gobi", "Sahara", "Atacama"], correcta: "Sahara" },
  { pregunta: "¿En qué país está la Torre Eiffel?", opciones: ["España", "Francia", "Alemania", "Inglaterra"], correcta: "Francia" },

  // --- DEPORTES (10) ---
  { pregunta: "¿Quién es considerado el mejor futbolista argentino?", opciones: ["Messi", "Maradona", "Batistuta", "Di Stéfano"], correcta: "Messi" },
  { pregunta: "¿En qué deporte se usa un aro y una pelota grande?", opciones: ["Básquet", "Fútbol", "Hockey", "Vóley"], correcta: "Básquet" },
  { pregunta: "¿Cuántos jugadores tiene un equipo de fútbol en cancha?", opciones: ["10", "11", "12", "9"], correcta: "11" },
  { pregunta: "¿Qué país ganó la Copa Mundial de Fútbol en 2018?", opciones: ["Brasil", "Alemania", "Francia", "Argentina"], correcta: "Francia" },
  { pregunta: "¿En qué deporte se utiliza la raqueta?", opciones: ["Tenis", "Fútbol", "Natación", "Ciclismo"], correcta: "Tenis" },
  { pregunta: "¿Cuántos minutos dura un partido de fútbol profesional?", opciones: ["90", "80", "100", "120"], correcta: "90" },
  { pregunta: "¿Qué país es famoso por la Fórmula 1 y Ferrari?", opciones: ["Alemania", "Italia", "Inglaterra", "España"], correcta: "Italia" },
  { pregunta: "¿En qué deporte se marca touchdown?", opciones: ["Rugby", "Fútbol americano", "Básquet", "Hockey"], correcta: "Fútbol americano" },
  { pregunta: "¿Qué atleta rompió récords de velocidad en 100 metros?", opciones: ["Usain Bolt", "Carl Lewis", "Michael Johnson", "Jesse Owens"], correcta: "Usain Bolt" },
  { pregunta: "¿Qué deporte se juega en Wimbledon?", opciones: ["Tenis", "Fútbol", "Básquet", "Golf"], correcta: "Tenis" },

  // --- MATEMÁTICA Y CONOCIMIENTO GENERAL (10) ---
  { pregunta: "¿Cuánto es 12 x 8?", opciones: ["96", "86", "108", "112"], correcta: "96" },
  { pregunta: "¿Cuál es el número primo más pequeño?", opciones: ["0", "1", "2", "3"], correcta: "2" },
  { pregunta: "¿Cuánto es 50 ÷ 5?", opciones: ["10", "15", "5", "12"], correcta: "10" },
  { pregunta: "¿Qué símbolo representa la suma?", opciones: ["-", "+", "×", "÷"], correcta: "+" },
  { pregunta: "¿Qué continente tiene más países?", opciones: ["África", "Asia", "Europa", "América"], correcta: "África" },
  { pregunta: "¿Qué país tiene más habitantes de habla hispana?", opciones: ["México", "España", "Argentina", "Colombia"], correcta: "México" },
  { pregunta: "¿Cuánto es 7²?", opciones: ["49", "42", "36", "56"], correcta: "49" },
  { pregunta: "¿Qué planeta es el segundo más cercano al Sol?", opciones: ["Mercurio", "Venus", "Tierra", "Marte"], correcta: "Venus" },
  { pregunta: "¿Qué día sigue al martes?", opciones: ["Lunes", "Miércoles", "Jueves", "Viernes"], correcta: "Miércoles" },
  { pregunta: "¿Qué país tiene la mayor superficie del mundo?", opciones: ["China", "Rusia", "EE.UU.", "Canadá"], correcta: "Rusia" }
];
